<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRENrNUz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRENrNUz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRENrNUz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRENrNUz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRENrNUz\App_KernelDevDebugContainer([
    'container.build_hash' => 'RENrNUz',
    'container.build_id' => '8c37733d',
    'container.build_time' => 1708339456,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRENrNUz');
