<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE4WvlrY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE4WvlrY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerE4WvlrY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerE4WvlrY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerE4WvlrY\App_KernelDevDebugContainer([
    'container.build_hash' => 'E4WvlrY',
    'container.build_id' => '3f3d46fc',
    'container.build_time' => 1708337546,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE4WvlrY');
