<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRENrNUz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRENrNUz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRENrNUz.legacy');

    return;
}
return new \ContainerRENrNUz\App_KernelDevDebugContainer([
    'container.build_hash' => 'RENrNUz',
    'container.build_id' => '7d6808b5',
    'container.build_time' => 1708516376,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRENrNUz');
